stages:
  data_cleaning:
    cmd: python E:/projects/Delivery-time-prediction-for-food-devlivery-industry/main_dvc.py
    deps:
    - E:/projects/Delivery-time-prediction-for-food-devlivery-industry/artifacts/data_ingestion/swiggy.csv
    - E:/projects/Delivery-time-prediction-for-food-devlivery-industry/src/Deliveryprediction/components/_3_data_cleaning.py
  
    outs:
    - artifacts\data_cleaning\swiggy_cleaned.csv