stages:
  data_cleaning:
    cmd: python E:/projects/Delivery-time-prediction-for-food-devlivery-industry/main_dvc.py
    deps:
    - E:/projects/Delivery-time-prediction-for-food-devlivery-industry/artifacts/data_ingestion/swiggy.csv
    - E:/projects/Delivery-time-prediction-for-food-devlivery-industry/src/Deliveryprediction/components/_3_data_cleaning.py
  
    outs:
    - artifacts\data_cleaning\swiggy_cleaned.csv

  data_preparation:
    cmd: python E:/projects/Delivery-time-prediction-for-food-devlivery-industry/main_dvc.py
    params:
    - PARAMS.test_size
    - PARAMS.random_state
    deps:
    - artifacts\data_cleaning\swiggy_cleaned.csv
    - E:\projects\Delivery-time-prediction-for-food-devlivery-industry\src\Deliveryprediction\components\step_4_data_preparation.py
    outs:
    - artifacts\data_preparation\train.csv
    - artifacts\data_preparation\test.csv

  data_transformation:
   cmd: python E:/projects/Delivery-time-prediction-for-food-devlivery-industry/main_dvc.py
   deps:
    - artifacts\data_cleaning\swiggy_cleaned.csv
    - E:\projects\Delivery-time-prediction-for-food-devlivery-industry\src\Deliveryprediction\components\step_5_data_transformation.py
   outs:
    - artifacts\data_trans\test_trans.csv
    - artifacts\data_trans\train_trans.csv
    - artifacts\data_trans\models\preprocessor.joblib
    
