artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://raw.githubusercontent.com/onkar-git/Delivery-time-prediction-for-food-delivery-industry/refs/heads/main/swiggy.csv"
  local_data_file: artifacts/data_ingestion/swiggy.csv
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/swiggy.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_cleaning:
  root_dir: artifacts/data_cleaning
  data_input_dir: artifacts/data_ingestion/swiggy.csv
  preprocess_data_dir: artifacts/data_cleaning/swiggy_cleaned.csv

data_preparation:
  root_dir: artifacts/data_preparation
  data_input_dir: artifacts/data_cleaning/swiggy_cleaned.csv
  train_dir: artifacts/data_preparation/
  test_dir: artifacts/data_preparation/

data_transformation:
  root_dir: artifacts/data_trans/
  data_input_dir: artifacts/data_preparation/
  data_tran_dir: artifacts/data_trans/


model_trainer:
  root_dir: artifacts/model_trainer/
  data_input_dir: artifacts/data_trans/
  train_data_path: artifacts/data_trans/
  test_data_path: artifacts/data_trans/
  test_model_dir: artifacts/model_trainer/
  model_name: model.joblib


model_evaluation:
 root_dir: artifacts/model_trainer/
 data_input_dir: artifacts/data_trans/
 model_path: artifacts/model_trainer/models/model.joblib
 metric_file: artifacts/model_evaluation/metrics.json
 prepro_dir: artifacts/data_trans/models/preprocessor.joblib

model_registry:
 dagshu_tracking_uri: "https://dagshub.com/onkar-git/Delivery-time-prediction-for-food-delivery-industry.mlflow"
 run_json_info: artifacts/model_evaluation/metrics.json
 repo_owner: 'onkar-git'
 repo_name: 'Delivery-time-prediction-for-food-delivery-industry'