artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://raw.githubusercontent.com/onkar-git/Delivery-time-prediction-for-food-delivery-industry/refs/heads/main/swiggy.csv"
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion
