artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://raw.githubusercontent.com/onkar-git/Delivery-time-prediction-for-food-delivery-industry/refs/heads/main/swiggy.csv"
  local_data_file: artifacts/data_ingestion/swiggy.csv
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/swiggy.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_cleaning:
  root_dir: artifacts/data_cleaning
  data_input_dir: artifacts/data_ingestion/swiggy.csv
  preprocess_data_dir: artifacts/data_cleaning/swiggy_cleaned.csv

data_preparation:
  root_dir: artifacts/data_preparation
  data_input_dir: artifacts/data_cleaning/swiggy_cleaned.csv
  train_dir: artifacts/data_preparation/
  test_dir: artifacts/data_preparation/

